language: php

php:
  - 7.1

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - pear install pear/PHP_CodeSniffer

script:
  - php artisan key:generate
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  - vendor/bin/phpunit

services:
  - redis-server

cache:
  directories:
    - vendor