language: php

php:
  - 7.1

install:
  - composer install --no-interaction

before_script:
  - cp .env.travis .env
  - composer self-update

script:
  - php artisan key:generate
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  - vendor/bin/phpunit

services:
  - redis-server

cache:
  directories:
    - vendor